### PR TITLE
Fix typo on env var OIDC_RENEW_ACCESS_TOKEN_ON_EXPIRY

### PR DESCRIPTION
**Pull request by gregnr**
Fixes typo on environment variable from `OIDC_RENEW_ACCESS_TOKEN_ON_EXPIERY` to `OIDC_RENEW_ACCESS_TOKEN_ON_EXPIRY`. Old environment variable still works for backwards compatibility, so no major version bump necessary.

### CODE REVIEW

**Comment by gregnr** [comment]
@Starefossen is this project active?

**Comment by Starefossen** [comment]
> @Starefossen is this project active?

It is still in use but we are always happy for more maintainers.

**Comment by Starefossen** [comment]
I need to make sure that Docker Hub is building, will check that later. Currently on mobile right now.

**Comment by gregnr** [comment]
@Starefossen Thanks for merging this in! Any update on the Docker build? I am still only seeing v1.3.0.

**Pull request merged**
