### PR TITLE
Add PKCE support

### PR DESCRIPTION
**Pull request by R0Wi**
Since https://github.com/zmartzone/lua-resty-openidc/pull/320 is now merged in the `lua-resty-openidc`-project, we can now use `use_pkce` variable to optionally enable PKCE support like described in this draft: https://tools.ietf.org/html/draft-parecki-oauth-v2-1-01.

**Note:** do not merge this PR until the next version of `lua-resty-openidc` (which is hopefully `1.7.3`) is released. Currently the patch is only available in the master-branch of the mentioned project.

### CODE REVIEW

**Comment by zandbelt** [comment]
lua-resty-openidc 1.7.3 is now released, which includes support for PKCE, see: https://github.com/zmartzone/lua-resty-openidc/releases/tag/v1.7.3

**Comment by R0Wi** [comment]
Ok then this should work. I tested it with my personal fork.

**Comment by R0Wi** [comment]
@zandbelt any chance to get this merged?

**Comment by zandbelt** [comment]
> @zandbelt any chance to get this merged?

I'm not the repo owner, this is a docker-oidc-proxy matter, not lua-resty-openidc

**Comment by R0Wi** [comment]
Sorry, forgot to check maintainers. Maybe @Starefossen could have an eye on this?

**Comment by Starefossen** [comment]
No longer employed by @evry unfortunately 😢  Maybe @AndersRunningen, @bjorges, @ekarlso, or @varneberg could have a look at this? 🙏🏻

**Review by bjorges — APPROVED** [review]
LGTM

**Pull request merged**
